spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jna?serverTimezone=UTC
    username: root
    password: 4869Sonic4062

mybatis:
  mapperLocations: classpath*:/mapper/*.xml
  configuration:
    mapUnderscoreToCamelCase: true